theme: jekyll-theme-minimal
title: Reading.Black
description: A diverse literature for SEED
url: https://socialresponsibility.github.io
baseurl: /reading.black
permalink: /:title/
logo: https://social-responsibility.org/images/logo200.png
